### ISSUE TITLE
Drizzle install issues

### ISSUE THREAD

**Issue by joelsfoster** [sophiacodes/sweet#1]
Hi! I was peer-reviewing your project (great job btw!) and just wanted to let you know I had a nightmare of a time trying to get Drizzle (and related packages `drizzle-react` and `drizzle-react-components`) to install properly. I first ran across it during the initial `npm i`, which was coming from an issue with `fsevents 1.1.3` not playing nice with `node 10.8.0` so it falls back on compiling using `node-gyp`, which also fails. After a LOT of digging, I saw that `truffle unbox drizzle` was having critical unfixed issues, so in package.json I changed:
```
"drizzle": "1.1.5",
"drizzle-react": "1.1.0",
"drizzle-react-components": "1.1.0",
```
It worked! Just FYI.

**Comment by sophiacodes** [comment]
Hey! Thanks for the heads up!
